Fixed Exception caused by "HasMatchingGameplayTag"
Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp] [Line: 1517]
Failed to find function HasMatchingGameplayTag in BP_EnemyBase_C /Game/ThirdPerson/UEDPIE_0_Lvl_ThirdPerson.Lvl_ThirdPerson:PersistentLevel.BP_EnemyBase_C_UAID_244BFE8D75AC04E202_1434799855